language: python
python:
  - "3.6"
# command to install dependencies for test purposes.
# Pytest is only needed for development so install seperately
# from the requirements.
install:
  - "pip3 install nose"
  - "pip3 install -r requirements.txt"
script: "nosetests tests/go_test.py"
